This notebook is used to handle a manipulate the various datasets

In [2]:
import torch
import pandas as pd

import os 
import yfinance as yf

In [7]:
stocks: list[str] = sorted(os.listdir('./data/datasets/America_Stocks'))

In [12]:
s = stocks[1]
split = lambda s: s.split('_')[1]

In [11]:
tickers = sorted(list(map(split, stocks[:10])))
tickers

['AAAP', 'AABA', 'AAL', 'AAME', 'AAOI', 'AAON', 'AAPL', 'AAWW', 'AAXJ', 'AAXN']

In [75]:
import pandas as pd

# Get S&P 500 table from Wikipedia
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
tables = pd.read_html(url)

# The first table contains the company list
sp500_df = tables[0]

# Display the first rows

# Optional: Get just the ticker symbols
tickers = sp500_df['Symbol'].tolist()
print(tickers[:10], len(tickers))  # Print first 10 tickers


['MMM', 'AOS', 'ABT', 'ABBV', 'ACN', 'ADBE', 'AMD', 'AES', 'AFL', 'A'] 503


In [ ]:
from datetime import datetime

# initializing string
test_str = '1997-04-01'

# printing original string
print("The original string is : " + str(test_str))

# initializing format 
format = "%Y-%m-%d"

# checking if format matches the date 
res = True

# using try-except to check for truth value



The original string is : 1997-04-01


True

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAPS']: YFTzMissingError('possibly delisted; no timezone found')


NO DOWNLOAD: Possibly an invalid ticker.


In [22]:
def csv_file_from_ticker(ticker: str, dest_folder_path: str,filename: str,start_date, end_date, ) -> bool:
    df = yf.download(ticker, start=start_date, end=end_date)  # Invalid ticker
    if df.empty:
        return False
    df.columns = df.columns.get_level_values(0)
    df.to_csv(f"{dest_folder_path}/{filename}.csv", sep=',', index=True)
    return True


In [ ]:
def csv_dataset_from_tickers(tickers: list[str], dest_folder_path: str,start_date=None ,end_date=None , date_format='%Y-%m-%d'):
    # Check date format correctness
    absolute_path = os.path.join(os.getcwd(), dest_folder_path)
    if start_date is not None: bool(datetime.strptime(start_date, date_format)) 
    if end_date is not None: bool(datetime.strptime(end_date, date_format))
    if os.path.exists(absolute_path):
        print("Destination folder already exists...")
        #return
    else: 
        os.makedirs(absolute_path)
    print("Creating CSVs...")
    failed_tickers = []
    for ticker in tickers:
        res = csv_file_from_ticker(ticker, absolute_path, f"NASDAQ_{ticker}_30Y.csv",start_date, end_date)
        if res == False: failed_tickers.append(ticker)  
    if len(failed_tickers) > 0:
        print(f"Tickers that raised error: {failed_tickers}")
    print(f"CSVs created. You can find the files at {dest_folder_path}")

    

In [11]:
csv_dataset_from_tickers(tickers, '/home/mbisoffi/tests/TemporalGNNReview/code/data/datasets/stocks_CSVs/America_Stocks_Updated')

Destination folder already exists...


In [50]:
def update_american_stocks(path: str, dest: str, start_date = None, end_date = None):
    absolute_path = os.path.join(os.getcwd(), dest)
    if os.path.exists(absolute_path):
        print("Destination folder already exists")
        #return
    else:
        os.makedirs(absolute_path)
    print("Creating CSVs...")
    
    source_path = os.path.join(os.getcwd(), path)

    files = sorted(os.listdir(source_path))

    for file in files:
        if os.path.exists(os.path.join(absolute_path, file)):
            print("File {file} already exists... skipping...")
            continue
        splitted = file.split("_")
        market = splitted[0]
        ticker = splitted[1]
        y = splitted[2].split(".")[0]
        #print(market, ticker, y)
        res = csv_file_from_ticker(ticker, absolute_path, f"{market}_{ticker}_{y}",start_date, end_date)



In [51]:
update_american_stocks('./data/datasets/stocks_CSVs/America_Stocks','./data/datasets/stocks_CSVs/America_Stocks_Updated')

[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AABA']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:


['AAWW']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['AAXN']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:


Destination folder already exists
Creating CSVs...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...


['ABAC']: YFPricesMissingError('possibly delisted; no price data found  (1d 1926-07-06 -> 2025-06-11)')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABAX']: ValueError('Length mismatch: Expected axis has 2 elements, new values have 1 elements')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABDC']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABEOW']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABIL']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABIO']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed downl

File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...


[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ABY']: YFPricesMissingError('possibly delisted; no price data found  (1d 1926-07-06 -> 2025-06-11)')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACBI']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACERW']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACER']: YFTzMissingError('possibly delisted; no timezone found')


File {file} already exists... skipping...
File {file} already exists... skipping...


[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACFC']: ValueError('Length mismatch: Expected axis has 2 elements, new values have 1 elements')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACGLP']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACHN']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACIA']: YFTzMissingError('possibly delisted; no timezone found')


File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...
File {file} already exists... skipping...


[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACOR']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACRX']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACSF']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed

1 Failed download:
['ACST']: YFTzMissingError('possibly delisted; no timezone found')
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%*****

In [5]:
l = os.listdir("/home/mirco/Documents/Tesi/code/data/datasets/stocks_CSVs/America_Stocks")

In [1]:
import torch
path = "/home/mbisoffi/tests/TemporalGNNReview/code/data/datasets/graph/NYSE_Train_2016-05-01_2017-06-30_22/graph_0.pt"

In [3]:
sample1 = torch.load('/home/mbisoffi/tests/TemporalGNNReview/code/data/datasets/graph/NYSE_Train_2016-05-01_2017-06-30_22/graph_0.pt')
sample2 = torch.load('/home/mbisoffi/tests/TemporalGNNReview/code/data/datasets/graph/NYSE_Train_2016-05-01_2017-06-30_22/graph_1.pt')


/tmp/ipykernel_434511/1214349547.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  sample1 = torch.load('/home/mbisoffi/tests/TemporalGNNReview/code/data/datasets/graph/NY

In [16]:
sample1.x.reshape(1171, 5, 22).permute(0, 2, 1).shape

torch.Size([1171, 22, 5])

In [58]:
i = torch.argmax(sample1.y[i+1:])
sample1.x.reshape(1171, 5, -1)[i][0] ,  sample2.x.reshape(1171, 5, -1)[i][0], sample1.y[i], i


(tensor([3.4809, 3.4842, 3.4822, 3.4801, 3.4840, 3.4926, 3.4969, 3.4993, 3.5022,
         3.4835, 3.4926, 3.5090, 3.5001, 3.4928, 3.4935, 3.4935, 3.4982, 3.5063,
         3.5105, 3.4975, 3.4990, 3.4868]),
 tensor([3.4842, 3.4822, 3.4801, 3.4840, 3.4926, 3.4969, 3.4993, 3.5022, 3.4835,
         3.4926, 3.5090, 3.5001, 3.4928, 3.4935, 3.4935, 3.4982, 3.5063, 3.5105,
         3.4975, 3.4990, 3.4868, 3.4796]),
 tensor(0.),
 tensor(1))

In [61]:
torch.softmax(torch.randn(2,5), dim=1)

tensor([[0.3184, 0.1779, 0.3529, 0.0672, 0.0835],
        [0.4831, 0.1363, 0.1201, 0.1375, 0.1230]])

In [2]:
import torch
import torch.nn as nn

In [38]:
rnn = nn.RNN(input_size=5, hidden_size=2, num_layers=1, batch_first=True, bias=True)  

In [40]:
x = torch.randn(1, 10, 5)  # (batch_size, seq_len, input_size)
x

tensor([[[-0.4525, -0.2003,  0.3672, -0.2804, -0.7474],
         [ 1.5524, -0.9674, -0.1078, -2.3513,  1.2771],
         [-0.1133, -0.7108, -0.9099, -0.3002,  1.5188],
         [ 0.8927, -0.9661, -2.1423, -0.7019,  1.6006],
         [ 0.9812,  1.0626,  0.0228, -0.1853, -0.5532],
         [-1.2939, -1.9150,  1.0961, -0.1429,  0.1259],
         [ 0.4578,  0.6962, -0.1841, -1.4919,  0.7226],
         [ 0.9926,  1.0397, -0.2285, -0.7384,  1.9385],
         [ 1.4563,  0.3442,  0.5392,  0.9774, -1.7697],
         [-0.0702, -0.6192, -0.0195, -0.5877,  0.0410]]])

In [41]:
rnn.forward(x)  # (batch_size, seq_len, input_size)

(tensor([[[-0.3624,  0.7948],
          [ 0.7657, -0.8779],
          [ 0.7976,  0.8383],
          [ 0.4494,  0.2407],
          [-0.9726,  0.8355],
          [ 0.8250, -0.0474],
          [-0.2812,  0.6089],
          [-0.6487,  0.7583],
          [-0.9956,  0.7190],
          [ 0.2610,  0.5422]]], grad_fn=<TransposeBackward1>),
 tensor([[[0.2610, 0.5422]]], grad_fn=<StackBackward0>))

In [44]:
from torch.nn import Conv2d, Conv1d

In [70]:
conv_layer = Conv2d(in_channels=5, out_channels=10 , kernel_size=(1,1), stride=(1, 1))

In [71]:
x = torch.randn(1, 5, 14, 160)  # (batch_size, n_features, timestamps length, n_nodes)

In [72]:
conv_layer(x).shape

torch.Size([1, 10, 14, 160])

In [ ]:
import torch.nn.functional as F

In [ ]:
t4d = torch.empty(3, 3, 4, 2).shape
out = F.pad(t4d, (1,1), "constant", 0)

torch.Size([3, 3, 4, 2])